# Generated by Django 6.0 on 2026-02-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiagnosticLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("module_ids", models.TextField(blank=True, default="")),
                ("version", models.CharField(default="v0_1", max_length=20)),
            ],
        ),
    ]
