# Generated by Django 6.0 on 2026-02-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnostic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosticlead",
            name="full_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="diagnosticlead",
            name="organization",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
