# Generated by Django 6.0 on 2026-02-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnostic", "0002_diagnosticlead_full_name_diagnosticlead_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosticlead",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
