# Generated by Django 6.0 on 2026-03-05 16:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnostic", "0003_alter_diagnosticlead_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosticlead",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
