# Generated by Django 6.0 on 2026-08-10 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shsat", "0016_answer_essay_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="EssayEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evaluated_at", models.DateTimeField(auto_now_add=True)),
                ("evaluation_data", models.JSONField(default=dict)),
                ("feedback", models.TextField(blank=True, default="")),
                ("error", models.TextField(blank=True, default="")),
                (
                    "answer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation",
                        to="shsat.answer",
                    ),
                ),
            ],
        ),
    ]
