# Generated by Django 5.1.2 on 2026-01-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="summary",
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
