# Generated by Django 5.1.2 on 2026-01-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_article_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="related",
            field=models.ManyToManyField(
                blank=True, related_name="related_to", to="articles.article"
            ),
        ),
    ]
