# Generated by Django 5.1.2 on 2026-01-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_article_related"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="articles/covers/"
            ),
        ),
    ]
