# Generated by Django 6.0 on 2026-10-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_articleimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("shsat", "SHSAT"),
                    ("hunter", "Hunter"),
                    ("critical-thinking", "Critical Thinking"),
                ],
                default="",
                max_length=30,
            ),
        ),
    ]
