# Generated by Django 6.0 on 2026-03-18 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("source", models.CharField(blank=True, default="", max_length=200)),
                ("is_free", models.BooleanField(default=True)),
                ("is_published", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="CutoffScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_name", models.CharField(max_length=200)),
                ("school_short", models.CharField(max_length=50)),
                ("admissions_year", models.PositiveSmallIntegerField()),
                ("cutoff_score", models.PositiveSmallIntegerField()),
                ("approximate_seats", models.PositiveSmallIntegerField()),
            ],
            options={
                "ordering": ["-cutoff_score"],
                "unique_together": {("school_short", "admissions_year")},
            },
        ),
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "child_nickname",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "child_grade",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("target_schools", models.JSONField(blank=True, default=list)),
                (
                    "subscription_status",
                    models.CharField(default="free", max_length=20),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shsat_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManualScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("source_name", models.CharField(max_length=200)),
                ("ela_correct", models.PositiveSmallIntegerField()),
                ("ela_total", models.PositiveSmallIntegerField(default=57)),
                ("math_correct", models.PositiveSmallIntegerField()),
                ("math_total", models.PositiveSmallIntegerField(default=57)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_scores",
                        to="shsat.parent",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[("ELA", "ELA"), ("Math", "Math")], max_length=10
                    ),
                ),
                ("question_number", models.PositiveSmallIntegerField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("grid_in", "Grid-In"),
                        ],
                        default="multiple_choice",
                        max_length=20,
                    ),
                ),
                ("topic", models.CharField(blank=True, default="", max_length=100)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "passage_group_id",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "passage_title",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("passage_text", models.TextField(blank=True, default="")),
                ("question_text", models.TextField()),
                ("choice_a", models.TextField(blank=True, default="")),
                ("choice_b", models.TextField(blank=True, default="")),
                ("choice_c", models.TextField(blank=True, default="")),
                ("choice_d", models.TextField(blank=True, default="")),
                ("correct_answer", models.CharField(max_length=1)),
                ("explanation", models.TextField(blank=True, default="")),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="shsat.test",
                    ),
                ),
            ],
            options={
                "ordering": ["section", "question_number"],
                "unique_together": {("test", "section", "question_number")},
            },
        ),
        migrations.CreateModel(
            name="TestAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("started_with", models.JSONField(default=list)),
                ("total_seconds", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "ela_correct",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "math_correct",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("ela_scaled", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "math_scaled",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "composite_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="shsat.parent",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="shsat.test",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_answer",
                    models.CharField(blank=True, default="", max_length=1),
                ),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                ("is_flagged", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="shsat.question",
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="shsat.testattempt",
                    ),
                ),
            ],
            options={
                "unique_together": {("attempt", "question")},
            },
        ),
    ]
