# Generated by Django 6.0 on 2026-05-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shsat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["section", "stage", "question_number"]},
        ),
        migrations.AlterUniqueTogether(
            name="question",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="question",
            name="distractor_types",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="question",
            name="skill",
            field=models.CharField(
                blank=True,
                choices=[
                    ("grammar_mechanics", "Grammar & Mechanics"),
                    ("rhetoric_organization", "Rhetoric & Organization"),
                    ("literal_comprehension", "Literal Comprehension"),
                    ("inference_analysis", "Inference & Analysis"),
                    ("vocabulary", "Vocabulary in Context"),
                    ("number_operations", "Number & Operations"),
                    ("algebraic_reasoning", "Algebraic Reasoning"),
                    ("geometric_reasoning", "Geometric Reasoning"),
                    ("data_probability", "Data & Probability"),
                    ("multistep_reasoning", "Multi-step Reasoning"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="stage",
            field=models.CharField(
                choices=[
                    ("standard", "Standard"),
                    ("routing", "Routing"),
                    ("easy_module", "Easy Module"),
                    ("hard_module", "Hard Module"),
                ],
                default="standard",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="is_adaptive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="test",
            name="routing_threshold",
            field=models.FloatField(default=0.6),
        ),
        migrations.AddField(
            model_name="testattempt",
            name="ela_module",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="testattempt",
            name="math_module",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name="question",
            unique_together={("test", "section", "stage", "question_number")},
        ),
    ]
