# Generated by Django 6.0 on 2026-05-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shsat", "0002_alter_question_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.CharField(max_length=20),
        ),
    ]
