# Generated by Django 6.0 on 2026-05-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shsat", "0003_widen_correct_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="skill",
            field=models.CharField(
                blank=True,
                choices=[
                    ("punctuation", "Punctuation"),
                    ("usage_agreement", "Usage & Agreement"),
                    ("sentence_structure", "Sentence Structure"),
                    ("main_idea", "Main Idea & Central Claim"),
                    ("supporting_detail", "Supporting Detail"),
                    ("inference", "Inference & Implication"),
                    ("vocabulary", "Vocabulary in Context"),
                    ("authors_craft", "Author's Craft & Organization"),
                    ("number_operations", "Number & Operations"),
                    ("fractions_decimals_percents", "Fractions, Decimals & Percents"),
                    ("ratios_proportions", "Ratios & Proportions"),
                    ("algebra", "Algebra"),
                    ("functions_patterns", "Functions & Patterns"),
                    ("geometry", "Geometry"),
                    ("statistics_data", "Statistics & Data"),
                    ("probability", "Probability"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="stage",
            field=models.CharField(
                choices=[
                    ("routing", "Routing"),
                    ("easy_module", "Easy Module"),
                    ("hard_module", "Hard Module"),
                ],
                default="standard",
                max_length=15,
            ),
        ),
    ]
