# Generated by Django 6.0 on 2026-05-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shsat", "0005_update_skill_choices_v2"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="shsat/questions/"
            ),
        ),
    ]
