# Generated by Django 6.0 on 2026-06-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shsat", "0006_add_question_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="time_spent_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
