# Generated by Django 6.0 on 2026-06-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shsat", "0007_add_answer_time_spent"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
