# Generated by Django 6.0 on 2026-06-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shsat", "0008_add_test_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="skill",
            field=models.CharField(
                blank=True,
                choices=[
                    ("punctuation", "Punctuation"),
                    ("usage_agreement", "Usage & Agreement"),
                    ("sentence_structure", "Sentence Structure"),
                    ("main_idea", "Main Idea & Central Claim"),
                    ("supporting_detail", "Supporting Detail"),
                    ("evidence_selection", "Evidence Selection"),
                    ("inference", "Inference & Implication"),
                    ("vocabulary", "Vocabulary in Context"),
                    ("authors_craft", "Author's Craft & Organization"),
                    ("cross_passage_synthesis", "Cross-passage Synthesis"),
                    ("number_operations", "Number & Operations"),
                    ("ratios_proportions", "Ratios & Proportions"),
                    ("algebra", "Algebra & Functions"),
                    ("geometry", "Geometry"),
                    ("statistics_data", "Statistics & Data"),
                    ("probability", "Probability"),
                    ("multistep_word_problems", "Multi-step Word Problems"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
