# Generated by Django 6.0 on 2026-07-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shsat", "0009_skill_max_length_50"),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="has_paid",
            field=models.BooleanField(default=False),
        ),
    ]
