# Generated by Django 6.0 on 2026-07-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shsat", "0012_question_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="choice_e",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="test",
            name="exam_type",
            field=models.CharField(
                choices=[("shsat", "SHSAT"), ("hunter", "Hunter")],
                default="shsat",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("multiple_choice", "Multiple Choice"),
                    ("grid_in", "Grid-In"),
                    ("essay", "Essay"),
                ],
                default="multiple_choice",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="section",
            field=models.CharField(
                choices=[
                    ("ELA", "ELA"),
                    ("Math", "Math"),
                    ("reading_comprehension", "Reading Comprehension"),
                    ("quantitative_reasoning", "Quantitative Reasoning"),
                    ("math_achievement", "Math Achievement"),
                    ("writing", "Writing"),
                ],
                max_length=30,
            ),
        ),
    ]
