# Generated by Django 6.0 on 2026-07-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shsat", "0013_hunter_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="is_drill",
            field=models.BooleanField(default=False),
        ),
    ]
