# Generated by Django 6.0 on 2026-07-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shsat", "0014_add_is_drill_to_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="platform",
            field=models.CharField(
                choices=[("shsat", "SHSAT"), ("hunter", "Hunter")],
                default="shsat",
                max_length=10,
            ),
        ),
    ]
