# Generated by Django 6.0 on 2026-08-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shsat", "0015_add_platform_to_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="essay_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
