# Generated by Django 6.0 on 2026-08-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shsat", "0020_parent_hunter_has_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parent",
            name="platform",
            field=models.CharField(
                choices=[("shsat", "SHSAT"), ("hunter", "Hunter"), ("both", "Both")],
                default="shsat",
                max_length=10,
            ),
        ),
    ]
