# Generated by Django 6.0 on 2026-10-06 20:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shsat", "0021_update_platform_choices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("invite_code", models.CharField(max_length=12, unique=True)),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("canceled", "Canceled"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("student_limit", models.PositiveSmallIntegerField(default=5)),
                ("email_verified", models.BooleanField(default=False)),
                (
                    "email_verification_token",
                    models.UUIDField(default=uuid.uuid4, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TutorStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(blank=True, default="", max_length=100)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutors",
                        to="shsat.parent",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="shsat.tutor",
                    ),
                ),
            ],
            options={
                "unique_together": {("tutor", "parent")},
            },
        ),
    ]
