# Generated by Django 5.1.2 on 2026-01-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactmessage",
            options={"ordering": ["-submitted_at"]},
        ),
        migrations.RenameField(
            model_name="contactmessage",
            old_name="created_at",
            new_name="submitted_at",
        ),
        migrations.RemoveField(
            model_name="contactmessage",
            name="is_read",
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="path",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="source",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="name",
            field=models.CharField(max_length=120),
        ),
    ]
