# Generated by Django 6.0 on 2026-05-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_curriculumlead"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuleWaitlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Module waitlist signup",
                "verbose_name_plural": "Module waitlist signups",
                "ordering": ["-created_at"],
            },
        ),
    ]
