# Generated by Django 6.0 on 2026-05-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_module_waitlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Newsletter subscriber",
                "verbose_name_plural": "Newsletter subscribers",
                "ordering": ["-created_at"],
            },
        ),
    ]
