# Generated by Django 6.0 on 2026-08-24 13:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form_id", models.CharField(max_length=50, unique=True)),
                ("form_version", models.PositiveSmallIntegerField()),
                ("scoring_version", models.PositiveSmallIntegerField()),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.CharField(max_length=20)),
                (
                    "dimension",
                    models.CharField(
                        choices=[
                            ("U", "Uncertainty Handling"),
                            ("M", "Model Awareness"),
                            ("C", "Causal Reasoning"),
                            ("A", "Abstraction Control"),
                            ("E", "Epistemic Humility"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("tf_confidence_block", "True/False + Confidence Block"),
                            ("mc", "Multiple Choice"),
                            ("mc_multi", "Multiple Choice Multi-Part"),
                            ("select_all", "Select All That Apply"),
                            ("scope_grid", "Scope Grid"),
                            ("allocate", "Allocate"),
                            ("two_step", "Two-Step"),
                            ("open_text", "Open Text"),
                        ],
                        max_length=30,
                    ),
                ),
                ("tier", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("domain", models.CharField(blank=True, max_length=50)),
                ("tag", models.CharField(blank=True, max_length=100)),
                ("payload", models.JSONField()),
                ("scored", models.BooleanField(default=True)),
                ("field_test", models.BooleanField(default=False)),
                ("form_version", models.PositiveSmallIntegerField(default=1)),
                ("active", models.BooleanField(default=True)),
                ("position", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["position"],
                "unique_together": {("item_id", "form_version")},
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("form_version", models.PositiveSmallIntegerField(default=1)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                ("user_agent", models.TextField(blank=True)),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="axis5_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form_version", models.PositiveSmallIntegerField()),
                ("scoring_version", models.PositiveSmallIntegerField()),
                ("payload", models.JSONField()),
                ("quality_flags", models.JSONField(default=list)),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="axis5.session",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.JSONField()),
                ("ms_first", models.PositiveIntegerField(blank=True, null=True)),
                ("ms_total", models.PositiveIntegerField(blank=True, null=True)),
                ("n_changes", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responses",
                        to="axis5.item",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="axis5.session",
                    ),
                ),
            ],
            options={
                "unique_together": {("session", "item")},
            },
        ),
    ]
