# Generated by Django 6.0 on 2026-08-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("axis5", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="item_sequence",
            field=models.JSONField(default=list),
        ),
    ]
