# Generated by Django 6.0 on 2026-08-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("axis5", "0002_add_session_item_sequence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="dimension",
            field=models.CharField(
                choices=[
                    ("U", "Uncertainty Handling"),
                    ("M", "Model Awareness"),
                    ("C", "Causal Reasoning"),
                    ("A", "Abstraction Control"),
                    ("E", "Trust Distribution"),
                ],
                max_length=1,
            ),
        ),
    ]
