# Generated by Django 6.0 on 2026-08-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("axis5", "0003_alter_item_dimension"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="name",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
